# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: chat.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'chat.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import facade.base_pb2 as base__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nchat.proto\x1a\nbase.proto\"t\n\x14\x42\x61nChatMemberRequest\x12\x0e\n\x06sassId\x18\x01 \x01(\t\x12\x19\n\x07\x62\x61nType\x18\x02 \x01(\x0e\x32\x08.BanType\x12\x0e\n\x06\x63hatId\x18\x03 \x01(\x03\x12\x11\n\tchatTitle\x18\x04 \x01(\t\x12\x0e\n\x06userId\x18\x05 \x01(\x03\"E\n\x10LeaveChatRequest\x12\x0e\n\x06sassId\x18\x01 \x01(\t\x12\x0e\n\x06\x63hatId\x18\x02 \x01(\x03\x12\x11\n\tchatTitle\x18\x03 \x01(\t*$\n\x07\x42\x61nType\x12\x0e\n\nmembership\x10\x00\x12\t\n\x05tribe\x10\x01\x32p\n\x04\x43hat\x12/\n\tleaveChat\x12\x11.LeaveChatRequest\x1a\x0f.CommonResponse\x12\x37\n\rbanChatMember\x12\x15.BanChatMemberRequest\x1a\x0f.CommonResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'chat_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BANTYPE']._serialized_start=215
  _globals['_BANTYPE']._serialized_end=251
  _globals['_BANCHATMEMBERREQUEST']._serialized_start=26
  _globals['_BANCHATMEMBERREQUEST']._serialized_end=142
  _globals['_LEAVECHATREQUEST']._serialized_start=144
  _globals['_LEAVECHATREQUEST']._serialized_end=213
  _globals['_CHAT']._serialized_start=253
  _globals['_CHAT']._serialized_end=365
# @@protoc_insertion_point(module_scope)
